### ISSUE TITLE
For Listener Page

### ISSUE THREAD

**Issue by basakkadakalozu** [ipekmotorcu/MFA#5]
For Listener's main page (ListenerView class) these functionalities need to be added:

- When the music is clicked on it should open up a new page with music's name and time, like, dislike and reactions should be there.
- Like song functionality should be added.
- Fix the general look and problems of the page.

**Comment by ipekmotorcu** [comment]
When a music item is clicked, it opens a detailed page displaying the music's name, duration, and options for like and dislike.
Implemented a "like" feature that allows users to mark songs as liked. Additionally, liked songs now appear on the user's main page under a dedicated "Liked Songs" section.
